name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # every day at noon
jobs:
  Download-and-Make:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out this repo
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: mkdir -p build/
      - name: Fetch latest data from the API endpoint
        run: |-
          curl -s "https://author.cota.com/wp-json/acf/v2/options/" | jq '.' > build/acf-options.json
      - uses: actions/upload-artifact@v3
        with:
          name: acf-options.json
          path: build/acf-options.json

