name: GitHub Actions Demo
run-name: "Download Stuff; build the feed"
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # every day at noon, in whatever timezone Github uses
jobs:
  Download-and-Make:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out this repo
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: mkdir -p build/
      - name: Fetch latest data from the API endpoint
        run: |-
          bash ./scraper.bash
      - name: Parse scrape and update JSON
        run: |-
          php ./parse.php
      - name: Generate RSS feed
        run: |-
          php ./rss.php > rss.xml
      - name: "Save files"
        uses: actions/upload-artifact@v3
        with:
          name: acf-options.json
          path: build/acf-options.json
      - name: "Preserve php errors"
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: php-error.log
          path: ./php-error.log

